version: "3.4"
services:
  node-npm-9.10.0-5.8.0:
    image: node-npm:9.10.0-5.8.0
    build:
      context: .
      dockerfile: node-npm-9.10.0-5.8.0.Dockerfile
  angular.cli-1.7.3:
    depends_on:
      - node-npm-9.10.0-5.8.0
    image: angular.cli:1.7.3
    build:
      context: .
      dockerfile: angular.cli-1.7.3.Dockerfile
  ng-new:
    depends_on:
      - angular.cli-1.7.3
    image: angular.cli:1.7.3
    volumes:
      - type: volume
        source: ApplicationRootVolume
        target: /ApplicationRoot
      - AngularAppNodeModules:${ANGULAR_IN_DOCKER_NODE_MODULES_TARGET}
      - Docker-Compose-Startup-Order:/Startup-Order
    command: |
      bash -c '
      echo ng-new start;
      touch /Startup-Order/ng-new.start;
      cd /ApplicationRoot;
      ng new Angular-App;
      echo ng-new done return code = $$?;
      touch /Startup-Order/ng-new.done;'
  npm-install:
    depends_on:
      - ng-new
    image: angular.cli:1.7.3
    volumes:
      - type: volume
        source: ApplicationRootVolume
        target: /ApplicationRoot
      - AngularAppNodeModules:${ANGULAR_IN_DOCKER_NODE_MODULES_TARGET}
      - Docker-Compose-Startup-Order:/Startup-Order
    command: |
      bash -c '
      echo npm-install start;
      touch /Startup-Order/npm-install.start;
      while [[ ! -f /Startup-Order/ng-new.done || /Startup-Order/ng-new.done -ot /Startup-Order/ng-new.start ]]; do sleep 1; done;
      echo npm-install doing;
      cd /ApplicationRoot/Angular-App;
      npm install;
      echo npm-install done;
      touch /Startup-Order/npm-install.done;'
  ng-serve:
    depends_on:
      - npm-install
    image: angular.cli:1.7.3
    volumes:
      - type: volume
        source: ApplicationRootVolume
        target: /ApplicationRoot
      - AngularAppNodeModules:${ANGULAR_IN_DOCKER_NODE_MODULES_TARGET}
      - Docker-Compose-Startup-Order:/Startup-Order
    ports:
      - 80:80
    command: |
      bash -c '
      echo ng-serve start;
      while [[ ! -f /Startup-Order/npm-install.done || /Startup-Order/npm-install.done -ot /Startup-Order/npm-install.start ]]; do sleep 1; done;
      echo ng-serve doing;
      cd /ApplicationRoot/Angular-App;
      ng serve --verbose --progress --host 0.0.0.0 --port 80 --poll 1;'
volumes:
  ApplicationRootVolume:
    external: true
    name: ${SHARE_WINDOWS_FOLDER_TO_DOCKER_VOLUMENAME}
  AngularAppNodeModules:
    name: ${SHARE_WINDOWS_FOLDER_TO_DOCKER_DIRECTORY_FILTER_NAME}_node_modules_${SHARE_WINDOWS_FOLDER_TO_DOCKER_DIRECTORY_HASH}
  Docker-Compose-Startup-Order:
    name: ${SHARE_WINDOWS_FOLDER_TO_DOCKER_DIRECTORY_FILTER_NAME}_startup_order_${SHARE_WINDOWS_FOLDER_TO_DOCKER_DIRECTORY_HASH}
